### ISSUE TITLE
Remove the cluster client

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb-python#339]
The cluster client no longer makes sense with recent patches.

Don't forget:
- remove the example in the README.
- remove the section in api-documentation.rst

**Comment by PierreF** [comment]
Hi,
which recent patches do you refer to ?
Or are you referring to InfluxDB itself that no longer support cluster ?

we are still using InfluxDB 0.11 with cluster, and that feature of influxdb-python was useful to us :(

**Comment by aviau** [comment]
This refers to https://github.com/influxdata/influxdb-python/pull/354. It was removed because InfluxDB instances can no longer be considered as equivalent (in the open source version). You can't just write a point to another instance if one of them is down. And round robin does not make sense either.

https://github.com/influxdata/influxdb-relay Can come into help. One would use the python client to write to a relay instead of writing to any server in the pool.

**Comment by PierreF** [comment]
Fine, thanks for taking time to explain the removal.

I've created a PR (#396) to re-add the cluster in a legacy module with warning that state this cluster client must NOT be used with newer influxdb-relay cluster.

**Comment by Convolution** [comment]
We are using the latest commercial version of InfluxDB (v1.2 Enterprise) which does not rely on a relay server. This means the load balancing still needs to be done on the client, hence there is still a strong use case for the ClusterClient. The removal of this functionality means that we cannot upgrade to the latest release of influxdb-python. 

Are there any plans to support Influx-Enterprise?

**Comment by PierreF** [comment]
PR #396 should works with latest InfluxDB enterprise cluster, it only require that all nodes are equivalent: writing on one node is replicated by the node to the other nodes; reading from any node return the same data

But since the ClusterClient is still useful in Influxdb enterprise, maybe the PR should not move it to a "legacy" module, but not normal module and/or "enterprise" module (e.g. with due warning that it does not works with relay cluster). What do you think @aviau, should I update the PR in this way ?
