### ISSUE TITLE
Async write support

### ISSUE THREAD

**Issue by dskoda1** [influxdata/influxdb-python#406]
After looking through the client code and finding the writes as synchronous, I can't help but feel there should be options for writing asynchronously. Correct me if i'm wrong, but it was instead chosen to batch up data points to make up for this?

I only see two closed issues [ #181, #348 ] regarding async behavior, so I'm curious as to the maintainers reasons for choosing the purely sync direction.

**Comment by pkittenis** [comment]
Cannot speak for maintainers but from what I can see, use of `requests` library precludes async requests as async is not supported by `requests`.

That said, `requests` could be monkey patched by [gevent](https://github.com/gevent/gevent) in code using this library which would make all requests made by this project asynchronous.

However, not sure there is a use case for this for writes specifically, given that requests, async or no, will still need to be handled by influxdb which is already asynchronous.
Hundreds/thousands async writes thrown at influxdb will not make it very happy. Better write performance  can be had by using one long lived connection (an InfluxDBClient object) and batching writes to it instead.

That connection can be run in background by running it on a separate process, or greenlet/future, directly, to make it async.

Finally, async does not preclude batching or vice versa. Batching writes improves write performance regardless of async/sync behaviour.

**Comment by modqhx** [comment]
@pkittenis A similar question, which you've almost answered :) So I'm reading from a raspberry pi pins and sending the data over the network to influx db. Yes, batching is something I'm using, but the batch blocks the main python program when its sending the data / POST to the db for which I'm using some async lib for python 2.. The `Series helper` class does provide this batch writing, but how am i suppose to wrap this up in a try catch block? Since the wifi is very unstable and very occasionally the device loses internet connection. Any recommendations?

**Comment by pkittenis** [comment]
| That connection can be run in background by running it on a separate process, or greenlet/future, directly, to make it async.

In other words, if blocking the main program while writing is not wanted then the writing function will need to be run in background. Whether that is done via threading, multi processing, or in a gevent patched client is not important as in that case as there will only be one connection, where async benefits do not apply as much.

Retrying `requests` library does by itself, if you want it to retry forever you'll need to `try/except` the error and resend the request in your own code.

**Comment by renderit** [comment]
@pkittenis Thanks for that.. Using `threading` module for now. I understand `requests` library does it byself, since I'm want to write locally if there's connection error, I want to use `try except`; is it possible you can give a simple example? That's be really helpful.. 
Another possible idea was to tun `auto commit` option to `False` and have a separate counter when `SeriesHelper` is called let's say 100 times. Does that make sense?

**Comment by pkittenis** [comment]
This is not an appropriate place for general programming questions - might want to take this to stackoverflow or similar.

**Comment by gusutabopb** [comment]
@dskoda1 Although it is quite basic and not very well tested yet, I have just made a simple async InfluxDB client and made it public: https://github.com/plugaai/aioinflux

**Comment by xginn8** [comment]
closing this ticket to track in #452
