### ISSUE TITLE
Neither DataFrameClient nor InfluxDBClient will return more than 10k results

### ISSUE THREAD

**Issue by covertcodes** [influxdata/influxdb-python#419]
I've tried altering the number of results InfluxDB itself returns in the query string; this didn't work either.  I notice theres a chunked param to the query methods, but these are not documented and a quick look at the source leads me to believe they're unused?

**Comment by pkittenis** [comment]
Have implemented chunked responses [in this PR](https://github.com/influxdata/influxdb-python/pull/418). The other option is setting `max-row-limit` to 0 in influxdb config.

Not sure if this project is actively maintained though, will have to wait and see. In the meantime you can install the PR branch directly if you'd like.

Have need of it also for an influxdb graphite client, may have to point requirements to the fork instead of the official client.

**Comment by covertcodes** [comment]
I'll need portability so it's best that I stick with what's in pip.  Thanks for the status update, though.  If you know of any alternative (specifically, getting huge amounts of data from influxdb into a data frame easily), I'd love to hear about it.

Thanks again

**Comment by pkittenis** [comment]
For what it's worth, pip and its requirements.txt can refer to git repos directly, including branches, PRs, tags and so on.

Not aware of any other options.

**Comment by covertcodes** [comment]
Thanks for the info

**Comment by saroele** [comment]
I have the same issue, but only since we upgraded influxdb from 1.0 to 1.2.  I'm using influxdb-python 4.0.0.

**Comment by saroele** [comment]
I ammended the [PR of pkittenis](https://github.com/pkittenis/influxdb-python/pull/1) so the DataFrameClient now also correctly uses chunking. 
Tested, works for me.
