### ISSUE TITLE
integrate mypy

### ISSUE THREAD

**Issue by ronneke1996** [influxdata/influxdb-python#736]
It would be very nice to have static typing added to the library for a number of reasons.

* It makes it more clear how the library is used
* It will prevent (some) bugs
* And maybe more

http://mypy-lang.org/

**Comment by aviau** [comment]
I already use mypy extensively at work, so I'd love to see it happen here.

If somebody wants to do this, please don't open a giant PR that annotates all the code. I won't merge it.

Instead, open a PR that:
 - adds mypy to the CI
 - add MINIMAL typing, just enough so that it passes mypy's minimal checks:

```
[mypy]
ignore_missing_imports = True
warn_unused_ignores = True
warn_unused_configs = True
warn_redundant_casts = True
warn_no_return = True
no_implicit_optional = True
strict_equality = True
```

then we can iterate from that.
