### ISSUE TITLE
Feature request: `create_database` if database not exists

### ISSUE THREAD

**Issue by Zhenye-Na** [influxdata/influxdb-python#774]
Please support features to create database if the database does not exists.

SQL-like command is

```sql
CREATE DATABASE IF NOT EXISTS metrics
```

Currently the way to simulate is:

```python
dbs = client.get_list_database()
if metrics not in dbs:
    client.create_database(metrics)
else:
    # otherwise
```

I would love to discuss or make contribution to this feature.

Thanks!

**Comment by russorat** [comment]
@Zhenye-Na thanks for the issue. According to the InfluxDB Docs, trying to create a database that already exists: 

> If you attempt to create a database that already exists, InfluxDB does nothing and does not return an error.

https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#create-database

So it seems like you should just always run `client.create_database(metrics)` since getting the list of databases first is likely more expensive. What do you think?

**Comment by Zhenye-Na** [comment]
Hey @russorat ,

Maybe using a `try .. catch` is enough?
